drop table if exists Person;

create table Person
(
    id   int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100),
    age  int
);

insert into Person (name, age) values ('First Name', 19);
insert into Person (name, age) values ('Second Name', 7);
insert into Person (name, age) values ('Third Name', 25);
insert into Person(name, age) values ('Miles Alexander Teller', 35);
insert into Person (name, age) values ('Sylvester Stallone', 76);
insert into Person (name, age)  values ('Tom Cruise', 60);
insert into Person (name, age)  values ('Jackie Сhan', 68);